bundles = {}

[versions]
	protobuf = "3.25.3"
	protobuf-plugin = "0.9.4"
	sonarqube = "4.4.1.3373"
	assertj = "3.25.3"
	mockito = "5.10.0"
	checkstyle = "10.14.0"
	os-maven-plugin = "1.7.1"
	junit-jupiter = "5.10.2"
[plugins]
	[plugins.protobuf]
		id = "com.google.protobuf"

		[plugins.protobuf.version]
			ref = "protobuf-plugin"
	[plugins.sonarqube]
		id = "org.sonarqube"

		[plugins.sonarqube.version]
			ref = "sonarqube"
[libraries]
	[libraries.junit-params]
		name = "junit-jupiter-params"
		group = "org.junit.jupiter"

		[libraries.junit-params.version]
			ref = "junit-jupiter"
	[libraries.protobuf-java]
		name = "protobuf-java"
		group = "com.google.protobuf"

		[libraries.protobuf-java.version]
			ref = "protobuf"
	[libraries.protobuf-java-util]
		name = "protobuf-java-util"
		group = "com.google.protobuf"

		[libraries.protobuf-java-util.version]
			ref = "protobuf"
	[libraries.assertj]
		name = "assertj-core"
		group = "org.assertj"

		[libraries.assertj.version]
			ref = "assertj"
	[libraries.junit-engine]
		name = "junit-jupiter-engine"
		group = "org.junit.jupiter"

		[libraries.junit-engine.version]
			ref = "junit-jupiter"
	[libraries.mockito]
		name = "mockito-junit-jupiter"
		group = "org.mockito"

		[libraries.mockito.version]
			ref = "mockito"
